# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
load("@rules_cc//cc:defs.bzl", "cc_library")
load("//tests/utils/bazel:unit_test.bzl", "lm_cc_test")

cc_library(
    name = "control_provider",
    srcs = ["control_provider.cpp"],
    hdrs = ["control_provider.hpp"],
    include_prefix = "score/mw/launch_manager/control",
    strip_include_prefix = "/score/launch_manager/src/daemon/src/control",
    visibility = ["//score/launch_manager/src/daemon:__pkg__"],
    deps = [
        "//score/launch_manager/src/daemon/src/common:log",
        "//score/launch_manager/src/daemon/src/osal:ipc_comms",
        "//score/launch_manager/src/daemon/src/process_group_manager:irun_target_control",
        "//score/launch_manager/src/lm_control",
    ],
)

lm_cc_test(
    name = "control_provider_UT",
    srcs = ["control_provider_UT.cpp"],
    args = [
        "--service_instance_manifest",
        "$(rootpath control_provider_test_mw_com_config.json)",
    ],
    data = ["control_provider_test_mw_com_config.json"],
    deps = [
        ":control_provider",
        "//score/launch_manager:error",
        "//score/launch_manager/src/daemon/src/process_group_manager:irun_target_control",
        "@googletest//:gtest",
        "@score_baselibs//score/string_manipulation/arguments",
        "@score_communication//score/mw/com",
    ],
)
